# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = "bender"
  s.version = "0.0.3"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["E-Max"]
  s.date = "2012-05-15"
  s.description = "Deploying system"
  s.email = "emax@studentify.nl"
  s.extra_rdoc_files = [
    "LICENSE",
    "README.md"
  ]
  s.files = [
    ".rvmrc",
    ".travis.yml",
    "Gemfile",
    "Gemfile.lock",
    "LICENSE",
    "README.md",
    "Rakefile",
    "lib/undestroyable.rb",
    "lib/undestroyable/configuration.rb",
    "lib/undestroyable/connection.rb",
    "lib/undestroyable/orm.rb",
    "lib/undestroyable/orm/active_record.rb",
    "lib/undestroyable/orm/active_record/column.rb",
    "lib/undestroyable/orm/active_record/connection.rb",
    "lib/undestroyable/orm/active_record/database.rb",
    "lib/undestroyable/orm/active_record/dump.rb",
    "lib/undestroyable/orm/active_record/table.rb",
    "lib/undestroyable/strategies.rb",
    "test/cases/active_record_test/column_test.rb",
    "test/cases/active_record_test/database_test.rb",
    "test/cases/active_record_test/dump_test.rb",
    "test/cases/active_record_test/loading_test.rb",
    "test/cases/active_record_test/table_test.rb",
    "test/cases/configuration_test.rb",
    "test/config.rb",
    "test/data/activerecord_setup.rb",
    "test/data/countries_table.rb",
    "test/data/dump_table.rb",
    "test/temp/test.db",
    "undestroyable.gemspec"
  ]
  s.homepage = "http://github.com/kot-begemot/Bender"
  s.licenses = ["MIT"]
  s.require_paths = ["lib"]
  s.rubygems_version = "1.8.10"
  s.summary = "Deploying system connecting Heroku, Github, Gist and Jabber chat room."

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<rake>, [">= 0"])
      s.add_development_dependency(%q<activerecord>, [">= 0"])
      s.add_development_dependency(%q<jeweler>, ["~> 1.8.0"])
      s.add_development_dependency(%q<yard>, ["~> 0.8.1"])
    else
      s.add_dependency(%q<rake>, [">= 0"])
      s.add_dependency(%q<activerecord>, [">= 0"])
      s.add_dependency(%q<jeweler>, ["~> 1.8.0"])
      s.add_dependency(%q<yard>, ["~> 0.8.1"])
    end
  else
    s.add_dependency(%q<rake>, [">= 0"])
    s.add_dependency(%q<activerecord>, [">= 0"])
    s.add_dependency(%q<jeweler>, ["~> 1.8.0"])
    s.add_dependency(%q<yard>, ["~> 0.8.1"])
  end
end

